# Generated by Django 3.2.7 on 2022-08-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='solve_status',
            field=models.CharField(default='', max_length=2, null=True),
        ),
    ]
