# Generated by Django 3.2.7 on 2022-08-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_challenges_solve_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='solve_status',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
