# Generated by Django 3.2.7 on 2022-08-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20220817_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='hint',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
