# Generated by Django 3.2.7 on 2022-08-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_challenges_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='hint',
            field=models.TextField(default='', max_length=100),
        ),
    ]
