# Generated by Django 3.2.7 on 2022-08-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_challenges_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='link',
            field=models.CharField(default='dashboard', max_length=255),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='hint',
            field=models.CharField(default='', max_length=255),
        ),
    ]
