# Generated by Django 3.2.7 on 2022-08-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20220818_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='solve_status',
            field=models.CharField(default='', max_length=2),
        ),
    ]
